Updated CI scripts.

diff --git a/ci/before-install b/ci/before-install
--- a/ci/before-install
+++ b/ci/before-install
@@ -22,10 +22,16 @@
 . `dirname $0`/get-container
 
 
-# ###### Linux ##############################################################
-if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
+# ###### Linux as-is ########################################################
+if [ "${TRAVIS_OS_NAME}" == "linux" -a "${DOCKER}" == "" -a "${QEMU}" == "" ] ; then
 
-   if [ "${DOCKER}" != "" ] ; then
+   # Nothing to be done here.
+   true
+
+
+# ###### Linux via Docker ###################################################
+elif [ "${TRAVIS_OS_NAME}" == "linux" -a "${DOCKER}" != "" -a "${QEMU}" == "" ] ; then
+
       # NOTE: Using tmpfs for pbuilder and mock!
       # The build machine therefore needs a sufficient amount of RAM!
       sudo docker rm -f ${CONTAINER} || true
@@ -38,17 +44,46 @@ if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
          -v $(pwd):/travis -w /travis \
          $DOCKER tail -f /dev/null
       sudo docker ps
+
+
+# ###### FreeBSD via QEMU ###################################################
+elif [ "${TRAVIS_OS_NAME}" == "linux" -a "${QEMU}" == "FreeBSD" ] ; then
+   if [ "${VARIANT}" != "" ] ; then
+
+      sudo mkdir -p /vservers/qemu-freebsd
+      sudo chown $USER:$USER /vservers/qemu-freebsd
+      mkdir -p /vservers/qemu-freebsd/mnt
+      cd /vservers/qemu-freebsd
+
+      # ====== Download image ============================================
+      imageName="FreeBSD-${VARIANT}-amd64.raw"
+      if [ -e ${imageName}.xz -a ! -e ${imageName} ] ; then
+         echo "Extracting existing ${imageName}.xz ..."
+         xz -T0 -dk ${imageName}.xz
+      elif [ ! -e ${imageName}.xz -o ! -e ${imageName} ] ; then
+         imageURL="https://download.freebsd.org/ftp/releases/VM-IMAGES/${VARIANT}/amd64/Latest/${imageName}.xz"
+         echo "Downloading FreeBSD VM image from ${imageURL} ..."
+         curl "${imageURL}" | tee ${imageName}.xz.tmp | xz -T0 -d - >${imageName}
+         mv ${imageName}.xz.tmp ${imageName}.xz
+      fi
+
+      # ====== Download fuse-ufs2 ========================================
+      if [ ! -d fuse-ufs2/ ] ; then
+         echo "Downloading fuse-ufs2 ..."
+         git clone https://github.com/mkatiyar/fuse-ufs2
+      fi
    fi
 
 
-# ###### Other ##############################################################
+# ###### MacOS X ############################################################
 elif [ "${TRAVIS_OS_NAME}" == "osx" ] ; then
 
-   echo "Nothing to be done here."
+   # Nothing to be done here.
+   true
 
 
 # ###### Error ##############################################################
 else
-   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
+   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=${TRAVIS_OS_NAME}, DOCKER=${DOCKER}, QEMU=${QEMU}!"
    exit 1
 fi
diff --git a/ci/build b/ci/build
--- a/ci/build
+++ b/ci/build
@@ -22,57 +22,76 @@
 . `dirname $0`/get-container
 
 
-# ###### Linux ##############################################################
-if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
+# ###### Linux as-is ########################################################
+if [ "${TRAVIS_OS_NAME}" == "linux" -a "${DOCKER}" == "" -a "${QEMU}" == "" ] ; then
+   # ====== Configure with CMake ============================================
+   if [ -e CMakeLists.txt ] ; then
+      env CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
 
-   # ====== Docker ==========================================================
-   if [ "${DOCKER}" != "" ] ; then
-
-      if [ "${TOOL}" == "compile" ] ; then
-         echo "###### Compiling ... ##################################################"
-
-         if [ -e CMakeLists.txt ] ; then
-            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
-         elif [ -e configure.ac -o -e configure.in ] ; then
-            if [ -e bootstrap ] ; then
-               sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./bootstrap
-               sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
-            elif [ -e autogen.sh ] ; then
-               sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./autogen.sh
-            else
-               sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
-            fi
-         else
-            echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
-         fi
-
-         cores=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 getconf _NPROCESSORS_ONLN 2>/dev/null || true`
-         if [ $cores -gt 1 ] ; then
-            MAKEFLAGS="-j${cores}"
-         fi
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
-
-      elif [ "${TOOL}" == "pbuilder" ] ; then
-         echo "###### Running pbuilder ... ###########################################"
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 sed -e 's/SKIP_PACKAGE_SIGNING=0/SKIP_PACKAGE_SIGNING=1/g' -i packaging.conf
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 eatmydata ./build-deb
-
-      elif [ "${TOOL}" == "mock" ] ; then
-         echo "###### Running mock ... ###############################################"
-         release=`sudo docker exec -t ${CONTAINER} bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
-         arch=`sudo docker exec -t ${CONTAINER} env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_+-]//g"`
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 LD_PRELOAD=/usr/lib64/nosync/nosync.so sed -e 's/SKIP_PACKAGE_SIGNING=0/SKIP_PACKAGE_SIGNING=1/g' -i packaging.conf
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 LD_PRELOAD=/usr/lib64/nosync/nosync.so ./build-rpm fedora-${release}-${arch}
-
+   # ====== Configure with autoconf/automake (via bootstrap script) =========
+   elif [ -e configure.ac -o -e configure.in ] ; then
+      if [ -e bootstrap ] ; then
+         env CC=${COMPILER_C} CXX=${COMPILER_CXX} ./bootstrap
+         env CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+      elif [ -e autogen.sh ] ; then
+         env CC=${COMPILER_C} CXX=${COMPILER_CXX} ./autogen.sh
       else
-         echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
-         exit 1
+         env CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+      fi
+   else
+      echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
+   fi
+   cores=`getconf _NPROCESSORS_ONLN 2>/dev/null || true`
+   if [ $cores -gt 1 ] ; then
+      MAKEFLAGS="-j${cores}"
+   fi
+
+   # ====== Compile ======================================================
+   if [ "${TOOL}" == "compile" ] ; then
+      env MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
+
+   # ====== Coverity Scan ================================================
+   elif [ "${TOOL}" == "coverity" ] ; then
+      # ------ Build -----------------------------------------------------
+      cd coverity
+      export PATH="coverity/$(ls -d cov*)/bin:$PATH"
+      cd ..
+
+      env MAKEFLAGS=${MAKEFLAGS} cov-build --dir cov-int make
+      tar czf coverity-results.tar.gz cov-int
+      ls -l coverity-results.tar.gz
+
+      # ------ Upload results --------------------------------------------
+      if [ "${TRAVIS_BRANCH}" == "${COVERITY_SCAN_BRANCH}" ] ; then
+         curl --form token=${COVERITY_SCAN_TOKEN} \
+              --form email=${COVERITY_SCAN_NOTIFICATION_EMAIL} \
+              --form file=@coverity-results.tar.gz \
+              --form version="master branch head" \
+              --form description="$(git log -1|head -1)" \
+              https://scan.coverity.com/builds?project=${COVERITY_PROJECT}
+         CURL_RESULT=$?
+         echo "curl returned ${CURL_RESULT}"
+         if [ $CURL_RESULT -ne 0 ]; then
+            echo >&2 "ERROR: Upload to Coverity Scan failed; curl returned ${CURL_RESULT}!"
+            exit 1
+         fi
+      else
+         echo >&2 "###### NOTE: This branch \"${TRAVIS_BRANCH}\" is not the scan branch \"${COVERITY_SCAN_BRANCH}\"! Skipping upload! ######"
       fi
 
-
-   # ====== Travis CI standard Ubuntu Linux machine =========================
-   # That is: not using Docker
+   # ====== Invalid setting =================================================
    else
+      echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}!"
+      exit 1
+   fi
+
+
+# ###### FreeBSD via QEMU ###################################################
+elif [ "${TRAVIS_OS_NAME}" == "linux" -a "${QEMU}" == "FreeBSD" ] ; then
+
+   ssh -p 8829 -i ~/.ssh/id_rsa root@localhost <<EOF
+      cd /travis
+
       # ====== Configure ====================================================
       if [ -e CMakeLists.txt ] ; then
          env CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
@@ -88,52 +107,67 @@ if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
       else
          echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
       fi
-      cores=`getconf _NPROCESSORS_ONLN 2>/dev/null || true`
+
+      cores=\`sysctl -a | grep 'hw.ncpu' | cut -d ':' -f2 | tr -d ' '\`
+      if [ \${cores} -gt 1 ] ; then
+         MAKEFLAGS="-j\${cores}"
+      fi
+      echo "Running: env MAKEFLAGS=\${MAKEFLAGS} make"
+      env MAKEFLAGS=\${MAKEFLAGS} make || exit 1
+
+      echo "Done!"
+      exit 0
+EOF
+
+
+# ###### Linux via Docker ###################################################
+elif [ "${TRAVIS_OS_NAME}" == "linux" -a "${DOCKER}" != "" -a "${QEMU}" == "" ] ; then
+
+   # ====== Compile (generic) ===============================================
+   if [ "${TOOL}" == "compile" ] ; then
+      echo "###### Compiling ... ##################################################"
+
+      if [ -e CMakeLists.txt ] ; then
+         sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
+      elif [ -e configure.ac -o -e configure.in ] ; then
+         if [ -e bootstrap ] ; then
+            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./bootstrap
+            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+         elif [ -e autogen.sh ] ; then
+            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./autogen.sh
+         else
+            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+         fi
+      else
+         echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
+      fi
+
+      cores=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 getconf _NPROCESSORS_ONLN 2>/dev/null || true`
       if [ $cores -gt 1 ] ; then
          MAKEFLAGS="-j${cores}"
       fi
+      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
 
-      # ====== Compile ======================================================
-      if [ "${TOOL}" == "compile" ] ; then
-         env MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
+   # ====== pbuilder (Debian/Ubuntu variants) ===============================
+   elif [ "${TOOL}" == "pbuilder" ] ; then
+      echo "###### Running pbuilder ... ###########################################"
+      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 OVERRIDE_SKIP_PACKAGE_SIGNING=1 eatmydata ./build-deb
 
-      # ====== Coverity Scan ================================================
-      elif [ "${TOOL}" == "coverity" ] ; then
-         # ------ Build -----------------------------------------------------
-         cd coverity
-         export PATH="coverity/$(ls -d cov*)/bin:$PATH"
-         cd ..
+   # ====== mock (Fedora variants) ==========================================
+   elif [ "${TOOL}" == "mock" ] ; then
+      echo "###### Running mock ... ###############################################"
+      release=`sudo docker exec -t ${CONTAINER} bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
+      arch=`sudo docker exec -t ${CONTAINER} env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_+-]//g"`
+      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 LD_PRELOAD=/usr/lib64/nosync/nosync.so OVERRIDE_SKIP_PACKAGE_SIGNING=1 ./build-rpm fedora-${release}-${arch}
 
-         env MAKEFLAGS=${MAKEFLAGS} cov-build --dir cov-int make
-         tar czf coverity-results.tar.gz cov-int
-         ls -l coverity-results.tar.gz
-
-         # ------ Upload results --------------------------------------------
-         if [ "${TRAVIS_BRANCH}" == "${COVERITY_SCAN_BRANCH}" ] ; then
-            curl --form token=${COVERITY_SCAN_TOKEN} \
-                 --form email=${COVERITY_SCAN_NOTIFICATION_EMAIL} \
-                 --form file=@coverity-results.tar.gz \
-                 --form version="master branch head" \
-                 --form description="$(git log -1|head -1)" \
-                 https://scan.coverity.com/builds?project=${COVERITY_PROJECT}
-            CURL_RESULT=$?
-            echo "curl returned ${CURL_RESULT}"
-            if [ $CURL_RESULT -ne 0 ]; then
-               echo >&2 "ERROR: Upload to Coverity Scan failed; curl returned ${CURL_RESULT}!"
-               exit 1
-            fi
-         else
-            echo >&2 "###### NOTE: This branch \"${TRAVIS_BRANCH}\" is not the scan branch \"${COVERITY_SCAN_BRANCH}\"! Skipping upload! ######"
-         fi
-
-      else
-         echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
-         exit 1
-      fi
+   # ====== Invalid setting =================================================
+   else
+      echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}!"
+      exit 1
    fi
 
 
-# ###### Other ##############################################################
+# ###### MacOS X ############################################################
 elif [ "${TRAVIS_OS_NAME}" == "osx" ] ; then
 
    cmake . $@
@@ -142,6 +176,6 @@ elif [ "${TRAVIS_OS_NAME}" == "osx" ] ; then
 
 # ###### Error ##############################################################
 else
-   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
+   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=${TRAVIS_OS_NAME}, DOCKER=${DOCKER}, QEMU=${QEMU}!"
    exit 1
 fi
diff --git a/ci/test b/ci/test
--- a/ci/test
+++ b/ci/test
@@ -22,86 +22,108 @@
 . `dirname $0`/get-container
 
 
-# ###### Linux ##############################################################
-if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
+# ###### Linux as-is ########################################################
+if [ "${TRAVIS_OS_NAME}" == "linux" -a "${DOCKER}" == "" -a "${QEMU}" == "" ] ; then
 
-   # ====== Docker ==========================================================
-   if [ "${DOCKER}" != "" ] ; then
+   # Nothing to be done here.
+   true
 
-      # ====== pbuilder environment =========================================
-      if [ "$TOOL" == "pbuilder" ] ; then
-         CHANGELOG_HEADER="`head -n1 debian/changelog`"
-         PACKAGE=`echo ${CHANGELOG_HEADER} | sed -e "s/(.*//" -e "s/ //g"`
-         PACKAGE_VERSION=`echo ${CHANGELOG_HEADER} | sed -e "s/.*(//" -e "s/).*//" -e "s/ //g" -e "s/ //g" -e "s/^[0-9]://g"`
-         OUTPUT_VERSION=`echo ${PACKAGE_VERSION}   | sed -e "s/\(ubuntu\|ppa\)[0-9]*$/\1/"`
-         DEBIAN_VERSION=`echo ${OUTPUT_VERSION}    | sed -e "s/\(ubuntu\|ppa\)$//1"`
 
-         packages=""
-         if [ $#  -eq 0 ] ; then
-            echo "Looking for *${DEBIAN_VERSION}*.deb in /var/cache/pbuilder/result ..."
-            packages="`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 find /var/cache/pbuilder/result -name "*${DEBIAN_VERSION}*.deb"`"
-         fi
-         while [ $# -gt 0 ] ; do
-            echo "Looking for $1*${DEBIAN_VERSION}*.deb in /var/cache/pbuilder/result ..."
-            packages="${packages} `sudo docker exec ${CONTAINER} env LANG=C.UTF-8 find /var/cache/pbuilder/result -name "$1*${DEBIAN_VERSION}*.deb"`"
-            shift
-         done
-         packages=`echo "${packages}" | xargs -n1 | sort -u | xargs`
-         if [ "${packages}" == "" ] ; then
-            echo >&2 "ERROR: No packages have been found!"
-            exit 1
-         fi
+# ###### Linux via Docker ###################################################
+elif [ "${TRAVIS_OS_NAME}" == "linux" -a "${DOCKER}" != "" -a "${QEMU}" == "" ] ; then
 
-         echo "Installing ${packages} ..."
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive eatmydata apt-get install -fy ${packages} || {
-            echo "NOTE: apt-get failed -> trying dpkg instead of apt-get for local file!"
-            # NOTE: Older "apt-get" versions do not handle local files!
-            if ! sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive eatmydata dpkg -i ${packages} ; then
-               echo "There may be some dependencies missing. Trying to install them ..."
-               sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive eatmydata apt-get install -fy -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" --no-install-recommends
-               echo "Retrying to install ${packages} ..."
-               sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive eatmydata dpkg -i ${packages}
-            fi
-         }
-         echo "Done!"
+   # ====== pbuilder environment =========================================
+   if [ "$TOOL" == "pbuilder" ] ; then
+      CHANGELOG_HEADER="`head -n1 debian/changelog`"
+      PACKAGE=`echo ${CHANGELOG_HEADER} | sed -e "s/(.*//" -e "s/ //g"`
+      PACKAGE_VERSION=`echo ${CHANGELOG_HEADER} | sed -e "s/.*(//" -e "s/).*//" -e "s/ //g" -e "s/ //g" -e "s/^[0-9]://g"`
+      OUTPUT_VERSION=`echo ${PACKAGE_VERSION}   | sed -e "s/\(ubuntu\|ppa\)[0-9]*$/\1/"`
+      DEBIAN_VERSION=`echo ${OUTPUT_VERSION}    | sed -e "s/\(ubuntu\|ppa\)$//1"`
 
-      # ====== mock environment =============================================
-      elif [ "$TOOL" == "mock" ] ; then
-         PACKAGE=`grep "^Name:" rpm/*.spec | head -n1 | sed -e "s/Name://g" -e "s/[ \t]*//g"`
-         PACKAGE_VERSION=`grep "^Version:" rpm/*.spec | head -n1 | sed -e "s/Version://g" -e "s/[ \t]*//g"`
-
-         release=`sudo docker exec ${CONTAINER} bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
-         arch=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_+-]//g"`
-         if ! sudo docker exec ${CONTAINER} cd /var/lib/mock/fedora-${release}-${arch}/result ; then
-            if sudo docker exec ${CONTAINER} cd /var/lib/mock/fedora-rawhide-${arch}/result ; then
-               release="rawhide"
-            else
-               echo >&2 "ERROR: No results have been found!"
-               exit 1
-            fi
-         fi
-
-         packages=""
-         if [ $#  -eq 0 ] ; then
-            echo "Looking for *${PACKAGE_VERSION}*.rpm in /var/lib/mock/fedora-${release}-${arch}/result ..."
-            packages="`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 find /var/lib/mock/fedora-${release}-${arch}/result -name "*${PACKAGE_VERSION}*.rpm" | grep -v "\.src\.rpm$"`"
-         fi
-         while [ $# -gt 0 ] ; do
-            echo "Looking for $1*${PACKAGE_VERSION}*.rpm in /var/lib/mock/fedora-${release}-${arch}/result ..."
-            packages="${packages} `sudo docker exec ${CONTAINER} env LANG=C.UTF-8 find /var/lib/mock/fedora-${release}-${arch}/result -name "$1*${PACKAGE_VERSION}*.rpm" | grep -v "\.src\.rpm$"`"
-            shift
-         done
-         packages=`echo "${packages}" | xargs -n1 | sort -u | xargs`
-         if [ "${packages}" == "" ] ; then
-            echo >&2 "ERROR: No packages have been found!"
-            exit 1
-         fi
-
-         echo "Installing ${packages} ..."
-         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 LD_PRELOAD=/usr/lib64/nosync/nosync.so dnf install -y --allowerasing ${packages}
-         echo "Done!"
-
+      packages=""
+      if [ $#  -eq 0 ] ; then
+         echo "Looking for *${DEBIAN_VERSION}*.deb in /var/cache/pbuilder/result ..."
+         packages="`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 find /var/cache/pbuilder/result -name "*${DEBIAN_VERSION}*.deb"`"
+      fi
+      while [ $# -gt 0 ] ; do
+         echo "Looking for $1*${DEBIAN_VERSION}*.deb in /var/cache/pbuilder/result ..."
+         packages="${packages} `sudo docker exec ${CONTAINER} env LANG=C.UTF-8 find /var/cache/pbuilder/result -name "$1*${DEBIAN_VERSION}*.deb"`"
+         shift
+      done
+      packages=`echo "${packages}" | xargs -n1 | sort -u | xargs`
+      if [ "${packages}" == "" ] ; then
+         echo >&2 "ERROR: No packages have been found!"
+         exit 1
       fi
 
+      echo "Installing ${packages} ..."
+      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive eatmydata apt-get install -fy ${packages} || {
+         echo "NOTE: apt-get failed -> trying dpkg instead of apt-get for local file!"
+         # NOTE: Older "apt-get" versions do not handle local files!
+         if ! sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive eatmydata dpkg -i ${packages} ; then
+            echo "There may be some dependencies missing. Trying to install them ..."
+            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive eatmydata apt-get install -fy -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" --no-install-recommends
+            echo "Retrying to install ${packages} ..."
+            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive eatmydata dpkg -i ${packages}
+         fi
+      }
+      echo "Done!"
+
+   # ====== mock environment =============================================
+   elif [ "$TOOL" == "mock" ] ; then
+      PACKAGE=`grep "^Name:" rpm/*.spec | head -n1 | sed -e "s/Name://g" -e "s/[ \t]*//g"`
+      PACKAGE_VERSION=`grep "^Version:" rpm/*.spec | head -n1 | sed -e "s/Version://g" -e "s/[ \t]*//g"`
+
+      release=`sudo docker exec ${CONTAINER} bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
+      arch=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_+-]//g"`
+      if ! sudo docker exec ${CONTAINER} cd /var/lib/mock/fedora-${release}-${arch}/result ; then
+         if sudo docker exec ${CONTAINER} cd /var/lib/mock/fedora-rawhide-${arch}/result ; then
+            release="rawhide"
+         else
+            echo >&2 "ERROR: No results have been found!"
+            exit 1
+         fi
+      fi
+
+      packages=""
+      if [ $#  -eq 0 ] ; then
+         echo "Looking for *${PACKAGE_VERSION}*.rpm in /var/lib/mock/fedora-${release}-${arch}/result ..."
+         packages="`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 find /var/lib/mock/fedora-${release}-${arch}/result -name "*${PACKAGE_VERSION}*.rpm" | grep -v "\.src\.rpm$"`"
+      fi
+      while [ $# -gt 0 ] ; do
+         echo "Looking for $1*${PACKAGE_VERSION}*.rpm in /var/lib/mock/fedora-${release}-${arch}/result ..."
+         packages="${packages} `sudo docker exec ${CONTAINER} env LANG=C.UTF-8 find /var/lib/mock/fedora-${release}-${arch}/result -name "$1*${PACKAGE_VERSION}*.rpm" | grep -v "\.src\.rpm$"`"
+         shift
+      done
+      packages=`echo "${packages}" | xargs -n1 | sort -u | xargs`
+      if [ "${packages}" == "" ] ; then
+         echo >&2 "ERROR: No packages have been found!"
+         exit 1
+      fi
+
+      echo "Installing ${packages} ..."
+      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 LD_PRELOAD=/usr/lib64/nosync/nosync.so dnf install -y --allowerasing ${packages}
+      echo "Done!"
+
    fi
+
+
+# ###### FreeBSD via QEMU ###################################################
+elif [ "${TRAVIS_OS_NAME}" == "linux" -a "${QEMU}" == "FreeBSD" ] ; then
+
+    # FIXME: TBD!
+    true
+
+
+# ###### MacOS X ############################################################
+elif [ "${TRAVIS_OS_NAME}" == "osx" ] ; then
+
+   # Nothing to be done here.
+   true
+
+
+# ###### Error ##############################################################
+else
+   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=${TRAVIS_OS_NAME}, DOCKER=${DOCKER}, QEMU=${QEMU}!"
+   exit 1
 fi
